Fixed known bugs, dealt with naming problems and controller mappings.
onioncracker/spacey-backend-2021 pull request #11
Opened 2021-06-06 14:55 UTC by OleksandrShevchuk

2021-06-06 15:14 UTC, MJiason commented on src/main/java/com/heroku/spacey/controllers/EmployeeController.java
> +    @PostMapping
посилання

2021-06-06 15:17 UTC, MJiason commented on src/main/java/com/heroku/spacey/dao/impl/EmployeeDaoImpl.java
> +            employeeDto.setLoginId(rs.getInt("loginid"));
тут можна винести в метод

2021-06-06 15:17 UTC, MJiason commented on src/main/java/com/heroku/spacey/dao/impl/EmployeeDaoImpl.java
> +                employeeDto.setLoginId(resultSet.getInt("loginid"));
разом з цим

2021-06-06 15:24 UTC, MJiason commented on src/main/java/com/heroku/spacey/controllers/EmployeeController.java
> +        } catch (NotFoundException e) {
Ти можеш тут видалити воно само обробить ці помилки

2021-06-06 15:27 UTC, MJiason commented on src/main/java/com/heroku/spacey/controllers/EmployeeController.java
> +    @GetMapping("/search/{prompt}")
Ну і бажано зразу додай сек'юріті

2021-06-06 15:49 UTC, Dima2057 requested changes

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/controllers/EmployeeController.java
> +    }
Цю драбинку можна переписати простіше

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/dao/impl/EmployeeDaoImpl.java
> +            employeeDto.setLoginId(rs.getInt("loginid"));
Там папка з маперами є, можна створити окремий клас для мапінгу Employee

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/dao/impl/EmployeeDaoImpl.java
> +        String phonenumber = employeeDto.getPhoneNumber();
Для цих полів можна створити масив Object[] і туди передати елементи ці, потім в update передати зразу весь масив.

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/dao/impl/EmployeeDaoImpl.java
> +        String phonenumber = employeeDto.getPhoneNumber();
Для цих полів теж можна зробити масив, як писав вище

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/services/impl/EmployeeServiceImpl.java
> +        int pageSize = 20;
Ці змінні можна зробити константами, потім я додам окремий клас для констант і перемістимо їх туди.

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/services/impl/EmployeeServiceImpl.java
> +        return var != null && !var.isEmpty();
var з 11 джави застосовується як тип даних, краще перейменувати змінну.

2021-06-06 15:49 UTC, Dima2057 commented on src/main/java/com/heroku/spacey/services/impl/EmployeeServiceImpl.java
> +        return var != null && !var.isEmpty();
Там він ніби йде як ключове слово, дивно що помилки не сталось.

2021-06-06 15:49 UTC, Dima2057 commented on src/main/resources/sql/employee_queries.properties
> +insert_employee =           INSERT INTO login_info(email, userrole, firstname, lastname, status, phonenumber) \
(email, userrole, firstname, lastname, status, phonenumber) краще зробити з нового рядку

2021-06-07 06:28 UTC, Dima2057 approved these changes

2021-06-07 07:28 UTC, MJiason approved these changes

2021-06-07 07:31 UTC, merged